# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://ecemf.eu
title: European Climate and Energy Modelling Forum
email: wusher@kth.se
author: Will Usher
description: > # "Write an awesome description for your new site here.
  ECEMF is a Horizon 2020 funded project.
  The aim of the project is to establish a European focal-point – the forum - for energy and climate researchers and policy makers to tackle the key challenge of our time – how to achieve climate neutrality.
  The ECEMF consortium is led by KTH Royal Institute of Technology, and consists of 15 partners in total from 9 countries.
  Partners include CMCC, IIASA, PIK, TU Wien, e-think, TNO, Fraunhofer ISI, E3M, PBL, Artelys, Comillas, TU Delft, University of Melbourne and IOS-PIB.

copyright: 'Copyright &copy; 2021 Will Usher. All Rights Reserved.'
credits: This project has received funding from the European Union’s Horizon 2020 research and innovation programme under grant agreement No 101022622

  # 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: CommonMark
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ecemf_2020
  - title: github
    url: https://github.com/ecemf
  # - title: linkedin
  #   url:
